/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.koneksiController;
import controller.userController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author A S U S
 */
public class Register extends javax.swing.JFrame {

    private final DefaultTableModel model = new DefaultTableModel();
    private userController uc = new userController();

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();

        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJudul = new javax.swing.JLabel();
        inpNoTelp = new java.awt.TextField();
        inpUser = new java.awt.TextField();
        inpEmail = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inpAlamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        inpPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJudul.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(0, 102, 153));
        labelJudul.setText("Daftar ");
        labelJudul.setToolTipText("");
        getContentPane().add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 120, 30));

        inpNoTelp.setBackground(new java.awt.Color(253, 253, 253));
        inpNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpNoTelpKeyTyped(evt);
            }
        });
        getContentPane().add(inpNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 310, 20));

        inpUser.setBackground(new java.awt.Color(253, 253, 253));
        getContentPane().add(inpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 310, 20));

        inpEmail.setBackground(new java.awt.Color(253, 253, 253));
        getContentPane().add(inpEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 310, 20));

        jLabel7.setBackground(new java.awt.Color(109, 100, 100));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Username");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(109, 100, 100));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("No telp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel8.setBackground(new java.awt.Color(109, 100, 100));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        btnDaftar.setBackground(new java.awt.Color(0, 102, 153));
        btnDaftar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(204, 204, 204));
        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 120, 30));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, -1));

        inpAlamat.setBackground(new java.awt.Color(255, 255, 255));
        inpAlamat.setColumns(20);
        inpAlamat.setRows(5);
        jScrollPane2.setViewportView(inpAlamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 310, -1));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 210, -1));

        inpPass.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(inpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/washcloth.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 460, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private void populateTable() {
//        model.setRowCount(0);
//        try {
//            ArrayList<User> lihat = uc.tampilData();
//            for (User b : lihat) {
//                Object[] isiData = {b.getUsername(), b.getNoTelp(), b.getEmail()};
//                model.addRow(isiData);
//            }
//        } catch (SQLException ex) {
//            System.out.println("Eksepsi: " + ex.getMessage());
//            JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
//        }
//
//    }

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
//     int id = idText.getText();
        String nama = inpUser.getText();
        String noTelp = inpNoTelp.getText();
        String email = inpEmail.getText();
        String password = String.valueOf(inpPass.getPassword());
        String alamat = inpAlamat.getText();

        User user = new User(nama, noTelp, email, password, alamat);

//        Biodata bio = new Biodata();
        if (nama.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "nama harus diisi!");
        } else if (noTelp.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "no telp harus diisi!");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "email harus diisi!");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "password harus diisi");
        } else if (alamat.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "alamat harus diisi");
        } else if (btnDaftar.getText().equals("Daftar")) {
            try {
                if (uc.tambahData(user)) {
                    JOptionPane.showMessageDialog(this, "Berhasil Tambah Data");
                    Dashboard dashboard = new Dashboard();
                    dashboard.setVisible(true);
                    this.dispose();
//                    populateTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Tambah Data");
                }
            } catch (SQLException ex) {
                System.out.println("Eksepsi: " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
            }
        } else {
            try {
                int jawaban = JOptionPane.showConfirmDialog(this, "Ubah Data " + user.getUsername() + "?", "Ubah", JOptionPane.YES_NO_OPTION);
                if (jawaban == JOptionPane.YES_OPTION) {
                    if (uc.ubahData(user)) {
                        JOptionPane.showMessageDialog(this, "Berhasil Ubah Data");
                        Profile profile = new Profile();
                        profile.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal Ubah Data");
                    }
                }
            } catch (SQLException ex) {
                System.out.println("Eksepsi: " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
            }
        }
//       
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void inpNoTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpNoTelpKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_inpNoTelpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDaftar;
    public javax.swing.JTextArea inpAlamat;
    public java.awt.TextField inpEmail;
    public java.awt.TextField inpNoTelp;
    public javax.swing.JPasswordField inpPass;
    public java.awt.TextField inpUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelJudul;
    // End of variables declaration//GEN-END:variables
}
